name: Pipeline

on: [push]

env:
  APP_NAME: my_app

jobs:
  lint:
    runs-on: ubuntu-18.04

    steps:
      - name: checkout the code
        uses: actions/checkout@v1

      - name: set up python environment
        uses: actions/setup-python@v1.1.1

      - name: install requirements
        run: pip install --quiet -r requirements.txt
      
      - name: lint code
        run: |
          flake8 --ignore=E501,E231 *.py
          pylint --disable=C0301 --disable=C0326 *.py

      - name: run unit test
        run: |
          python -m unittest --verbose --failfast





    